language: php
os: linux
dist: trusty
php:
  - 8.0

before_script:
  - docker-compose build
  - docker-compose up -d
  - docker exec app composer install
  - sleep 10
  - docker exec -u root mysql chmod 777 /etc/mysql/scripts/migrate.sh
  - docker exec -u root mysql /etc/mysql/scripts/migrate.sh

script:
  - docker exec app bin/phpcs --standard=PSR12 src
  - docker exec app bin/phpcs --standard=PSR12 features
  - docker exec app bin/phpstan analyse features src
  - docker exec app bin/psalm
  - docker exec app bin/behat
