language: php
os: linux
dist: xenial
php:
  - 7.4.11

before_script:
  - docker-compose build
  - docker-compose up -d
  - sleep 15
  - docker exec -u root mysql chmod 777 /etc/mysql/scripts/migrate.sh
  - docker exec -u root mysql /etc/mysql/scripts/migrate.sh

script:
  - docker exec -it app bash -c "cd /var/www/my-garden/api && bin/phpstan analyse features src"
  - docker exec -it app bash -c "cd /var/www/my-garden/api && bin/psalm"
  - docker exec -it app bash -c "cd /var/www/my-garden/api && bin/behat"
