language: php
os: linux
dist: xenial
php:
  - 7.4.11

before_script:
  - cd api
  - composer install
  - cd ../ui/my-garden
  - npm install
  - cd ../../
  - docker-compose up -d
  - docker exec mysql /etc/mysql/scripts/migrate.sh

script:
  - cd api
  - bin/behat