language: php
os: linux
dist: xenial
php:
  - 7.4.11

before_script:
  - docker-compose build
  - docker-compose up -d
  - docker exec app composer install
  - docker exec -u root mysql chmod 777 /etc/mysql/scripts/migrate.sh
  - docker exec -u root mysql /etc/mysql/scripts/migrate.sh

script:
  - docker exec app bin/phpstan analyse features src -c phpstan.neon
  - docker exec app bin/psalm -c psalm.xml
  - docker exec app bin/behat
