language: php
os: linux
dist: xenial
php:
  - 7.4.11

before_script:
  - cd api
  - composer install
  - cd ../ui/my-garden
  - npm install
  - cd ../../
  - docker-compose up -d
  - docker exec -ti mysql sh
  - mysql -h "localhost" -u "root" -p"password" < /etc/mysql/scripts/migration.sql
  - exit

script:
  - cd api
  - bin/behat