version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: php-image
    container_name: app
    restart: unless-stopped
    tty: true
    volumes:
      - ./api/:/var/www/my-garden/api/
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    networks:
      - app-network

  #UI
  ui:
    build:
      context: ui/my-garden
      dockerfile: Dockerfile
##    image: vuejs/cli
    container_name: ui
#    restart: unless-stopped
#    tty: true
#    volumes:
#      - ./ui/:/var/www/my-garden/
#    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    #restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./api:/var/www/my-garden/
      - ./ui/:/var/www/my-garden/
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network

  #MySQL
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: unless-stopped
    user: "1000:50"
    volumes:
#      The line below is erroring as docker attempts to run --initialise but the folder has files in it
#      - /ProgramData/MySQL/MYSQL Server 8.0/Data:/var/lib/mysql
#      Instead, the line below is needed to place the migration file
      - ./api/src/Database/migration.sql:/etc/mysql/scripts/migration.sql
      - ./api/src/Database/migrate.sh:/etc/mysql/scripts/migrate.sh
#      docker exec -ti mysql sh
#      mysql -h "localhost" -u "root" -p"password" < /etc/mysql/scripts/migration.sql
    tty: true
    ports:
      - "3306:3306"
    networks:
      - app-network
    environment:
      MYSQL_ROOT_PASSWORD: "password"

#Docker Networks
networks:
  app-network:
    driver: bridge